/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.fitness.fitnessprojectt;

/**
 *
 * @author Emrecan
 */
public class studentMain extends javax.swing.JFrame {

    /**
     * Creates new form studentMain
     */
    public studentMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        bacakLabel = new javax.swing.JLabel();
        omuzLabel = new javax.swing.JLabel();
        gogusLabel = new javax.swing.JLabel();
        pazuLabel = new javax.swing.JLabel();
        belLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        humanBodyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(26, 22, 23));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));
        leftPanel.getAccessibleContext().setAccessibleName("leftPanel");

        rightPanel.setBackground(new java.awt.Color(24, 31, 28));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bacakLabel.setBackground(new java.awt.Color(255, 255, 255));
        bacakLabel.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        bacakLabel.setForeground(new java.awt.Color(131, 121, 11));
        bacakLabel.setText("Bacak: 61 CM");
        bacakLabel.setName("bacakLabel"); // NOI18N
        rightPanel.add(bacakLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 20));

        omuzLabel.setBackground(new java.awt.Color(255, 255, 255));
        omuzLabel.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        omuzLabel.setForeground(new java.awt.Color(131, 121, 11));
        omuzLabel.setText("Omuz: 131 CM");
        rightPanel.add(omuzLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 20));

        gogusLabel.setBackground(new java.awt.Color(255, 255, 255));
        gogusLabel.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        gogusLabel.setForeground(new java.awt.Color(131, 121, 11));
        gogusLabel.setText("Gogus: 114 CM");
        rightPanel.add(gogusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, 20));

        pazuLabel.setBackground(new java.awt.Color(255, 255, 255));
        pazuLabel.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        pazuLabel.setForeground(new java.awt.Color(131, 121, 11));
        pazuLabel.setText("Pazu: 42 CM");
        rightPanel.add(pazuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 20));

        belLabel.setBackground(new java.awt.Color(255, 255, 255));
        belLabel.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        belLabel.setForeground(new java.awt.Color(131, 121, 11));
        belLabel.setText("Bel: 79 Cm");
        rightPanel.add(belLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, 20));

        jLabel1.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(131, 121, 11));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emrecan\\Downloads\\weight (1).png")); // NOI18N
        jLabel1.setText("86 KG");
        rightPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        humanBodyLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emrecan\\Downloads\\standing-human-body-silhouette (1).png")); // NOI18N
        humanBodyLabel.setName("humanBodyLabel"); // NOI18N
        rightPanel.add(humanBodyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));
        humanBodyLabel.getAccessibleContext().setAccessibleName("humanBodyLabel");

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacakLabel;
    private javax.swing.JLabel belLabel;
    private javax.swing.JLabel gogusLabel;
    private javax.swing.JLabel humanBodyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel omuzLabel;
    private javax.swing.JLabel pazuLabel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
